package model;
// Generated Jun 22, 2016 1:19:40 PM by Hibernate Tools 4.3.1



/**
 * ArticuloRopaHasMaterialId generated by hbm2java
 */
public class ArticuloRopaHasMaterialId  implements java.io.Serializable {


     private int articuloRopaId;
     private int materialId;

    public ArticuloRopaHasMaterialId() {
    }

    public ArticuloRopaHasMaterialId(int articuloRopaId, int materialId) {
       this.articuloRopaId = articuloRopaId;
       this.materialId = materialId;
    }
   
    public int getArticuloRopaId() {
        return this.articuloRopaId;
    }
    
    public void setArticuloRopaId(int articuloRopaId) {
        this.articuloRopaId = articuloRopaId;
    }
    public int getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(int materialId) {
        this.materialId = materialId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArticuloRopaHasMaterialId) ) return false;
		 ArticuloRopaHasMaterialId castOther = ( ArticuloRopaHasMaterialId ) other; 
         
		 return (this.getArticuloRopaId()==castOther.getArticuloRopaId())
 && (this.getMaterialId()==castOther.getMaterialId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getArticuloRopaId();
         result = 37 * result + this.getMaterialId();
         return result;
   }   


}


