package model;
// Generated Jun 24, 2016 2:20:20 AM by Hibernate Tools 4.3.1



/**
 * ArticuloRopaHasMaterial generated by hbm2java
 */
public class ArticuloRopaHasMaterial  implements java.io.Serializable {


     private ArticuloRopaHasMaterialId id;
     private ArticuloRopa articuloRopa;
     private Material material;
     private double cantidad;

    public ArticuloRopaHasMaterial() {
    }

    public ArticuloRopaHasMaterial(ArticuloRopaHasMaterialId id, ArticuloRopa articuloRopa, Material material, double cantidad) {
       this.id = id;
       this.articuloRopa = articuloRopa;
       this.material = material;
       this.cantidad = cantidad;
    }
   
    public ArticuloRopaHasMaterialId getId() {
        return this.id;
    }
    
    public void setId(ArticuloRopaHasMaterialId id) {
        this.id = id;
    }
    public ArticuloRopa getArticuloRopa() {
        return this.articuloRopa;
    }
    
    public void setArticuloRopa(ArticuloRopa articuloRopa) {
        this.articuloRopa = articuloRopa;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }




}


