package model;
// Generated Jun 24, 2016 2:20:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private Integer materialId;
     private String nombre;
     private double cantidad;
     private double precioCostoPorYarda;
     private Set articuloRopaHasMaterials = new HashSet(0);

    public Material() {
    }

	
    public Material(String nombre, double cantidad, double precioCostoPorYarda) {
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.precioCostoPorYarda = precioCostoPorYarda;
    }
    public Material(String nombre, double cantidad, double precioCostoPorYarda, Set articuloRopaHasMaterials) {
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.precioCostoPorYarda = precioCostoPorYarda;
       this.articuloRopaHasMaterials = articuloRopaHasMaterials;
    }
   
    public Integer getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecioCostoPorYarda() {
        return this.precioCostoPorYarda;
    }
    
    public void setPrecioCostoPorYarda(double precioCostoPorYarda) {
        this.precioCostoPorYarda = precioCostoPorYarda;
    }
    public Set getArticuloRopaHasMaterials() {
        return this.articuloRopaHasMaterials;
    }
    
    public void setArticuloRopaHasMaterials(Set articuloRopaHasMaterials) {
        this.articuloRopaHasMaterials = articuloRopaHasMaterials;
    }




}


