package model;
// Generated Jun 22, 2016 1:19:40 PM by Hibernate Tools 4.3.1



/**
 * Planta generated by hbm2java
 */
public class Planta  implements java.io.Serializable {


     private Integer plantaId;
     private int capacidad;

    public Planta() {
    }

    public Planta(int capacidad) {
       this.capacidad = capacidad;
    }
   
    public Integer getPlantaId() {
        return this.plantaId;
    }
    
    public void setPlantaId(Integer plantaId) {
        this.plantaId = plantaId;
    }
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }




}


